### PR TITLE
(GH-50) Fix support for Oracle Linux

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Solves #50

**Comment by ghoneycutt** [comment]
@tomnowak Could you please test this patch and let us know how it goes.

**Comment by tomnowak** [comment]
I have tested the patch on the following OSed and all looked good:
 - RHEL 6 and 7
 - OracleLinux 6 and 7

I no longer see errors reported by Puppet on Oracle Linux.

Thanks,
Tomasz

**Comment by sgnl05** [comment]
Thanks!

**Pull request merged**
