### PR TITLE
Add service_ensure option to allow control of services running or not

### PR DESCRIPTION
**Pull request by sd-robbruce**

### CODE REVIEW

**Comment by sgnl05** [comment]
Change looks good, except for $sssd_service which is removed from init.pp. Any reason for this?

**Comment by sd-robbruce** [comment]
My bad, that what I was originally going to call the service_ensure parameter. Added it back in

**Comment by sgnl05** [comment]
Ok then. Good contribution, thanks! :)

**Comment by edestecd** [comment]
Is  $sssd_ensure used?

**Comment by edestecd** [comment]
I see $sssd_ensure defined in init.pp, but I don't see it being used anywhere else.
Am I missing it?

**Comment by sgnl05** [comment]
Good catch @edestecd 

It's not used anywhere. Probably an early variable name that was renamed to $ensure

**Pull request merged**
