### PR TITLE
Rhel8

### PR DESCRIPTION
**Pull request by robertc99**
start new pull request. Last one stopped running travis.
I thought I was supposed to be able to squash commits.
But I don't see a control for that.

### CODE REVIEW

**Comment by robertc99** [comment]
This branch still isnt running travis.

**Comment by sgnl05** [comment]
Error on Travis CI: "Could not parse sgnl05/sgnl05-sssd/.travis.yml@6ee94ef9923cbd11"

Warnings for .travis.yml:
[x] in matrix.include section: unexpected key sudo, dropping
[x] in matrix.include section: unexpected key services, dropping
[x] in matrix.include section: unexpected key bundler_args, dropping
[x] in matrix.include section: unexpected key script, dropping

Not sure what causes this. Still looking into it.

**Comment by dacron** [comment]
bumpity.

**Comment by robertc99** [comment]
I have no idea what the problem with this branch is.
I'd like to see it merged in upstream but have no idea how to achieve this.

**Comment by sgnl05** [comment]
Travis stopped working and I have no idea what went wrong. Seems to have fixed it self now!

Thanks for your contribution, and sorry for taking so long to merge it!

**Comment by robertc99** [comment]
You should probably test it for centos8 compatibility. When I did the work, centos8 wasnt out yet and I'd be surprised if it worked.

**Pull request merged**
