### PR TITLE
Add support for Ruby v2.3.1

### PR DESCRIPTION
**Pull request by ghoneycutt**
This is needed to support the new Puppet v4 AIO.

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Whew! Finally got it.

**Comment by ghoneycutt** [comment]
Hi @sgnl05 could you please merge this

**Comment by sgnl05** [comment]
Ofc, thanks!

**Comment by ghoneycutt** [comment]
Thank you very much! Could you please tag a new release.

**Pull request merged**
