### PR TITLE
Messagebus fix

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
I upgraded from 8efc6268df57cdefbb50791e1a7d887ca2d7ac24 to v1 and noticed that it introduced a bug regarding the ordering of messagebus and oddjobd. This set of commits is to address that.

**Comment by ghoneycutt** [comment]
@sgnl05 I'm using this patch in production to allow EL6 systems to continue to work with this module after upgrading. Could you please merge this?

**Comment by sgnl05** [comment]
Thanks!

**Comment by ghoneycutt** [comment]
@sgnl05 could you please tag a new release

**Comment by ghoneycutt** [comment]
Should be '1.0.1' as this is only a bug fix.

**Pull request merged**
