### PR TITLE
Setting ensure => absent now further disables sssd

### PR DESCRIPTION
**Pull request by machad**
* For redhat-based systems, authconfig flags --disablesssd and --disablesssdauth
* The sssd service sets ensure => stopped and enable => false

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Hi @machad 

Try running `puppet-lint -f manifests/*` to automatically fix the style issues. That should make Travis happy.

**Comment by machad** [comment]
@ghoneycutt Thanks. I've done that and committed the update. How do I trigger a re-check with travis?

**Comment by machad** [comment]
It looks like the following test is failing:

https://travis-ci.org/sgnl05/sgnl05-sssd/jobs/204363675

Unfortunately, it's a bit unclear to me where the actual issue is short of maybe something specific to Ruby 1.9.3. If you can give me a hint, I'll be happy to dig in.

**Comment by edestecd** [comment]
We meed a new exclude in the .travis.yml file. Apparently the newest version of puppet 4.9.x does not support ruby 1.9.3...

**Comment by edestecd** [comment]
Adding this should do it:

```
- rvm: 1.9.3
  env: PUPPET_GEM_VERSION="~> 4" CHECK=test
```

**Comment by ghoneycutt** [comment]
opened PR #33 to fix this issue

**Comment by ghoneycutt** [comment]
@edestecd Puppet 4.9 also drops support for ruby 2.0.0, though this module does not support that version.

**Comment by machad** [comment]
Thanks, @ghoneycutt. I'll keep an eye on that and once it's merged I'll pull it into this branch.

**Comment by sgnl05** [comment]
Thanks! :+1:

**Pull request merged**
